#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    relativenumber = false
    lint_on_the_fly = true
    enable_vimfiler_welcome = false
    default_indent = 4

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 46

[[layers]]
name = "sudo"

[[layers]]
name = "lang#python"
pydocstring_doq_path = "${HOME}/.pyenv/shims/doq"

[[layers]]
name = "lang#c"

[[layers]]
name = "denite"
# <Leader> f <Space>  Fuzzy find menu:CustomKeyMaps
# <Leader> f p        Fuzzy find menu:AddedPlugins
# <Leader> f e        Fuzzy find register
# <Leader> f h        Fuzzy find history/yank
# <Leader> f j        Fuzzy find jump, change
# <Leader> f l        Fuzzy find location list
# <Leader> f m        Fuzzy find output messages
# <Leader> f o        Fuzzy find outline
# <Leader> f q        Fuzzy find quick fix
# <Leader> f r        Fuzzy find Unite window

[[layers]]
name = "tmux"

[[layers]]
name = "fzf"

[[layers]]
name = "gtags"
gtagslabel = "pygments"

[[layers]]
name = "git"
